---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infra
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
