---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  resources:
    - 1-configmap/wp-configmap.yaml
    - 2-secret/wp-secret.yaml
    - 3-volumes/backend-claim.yaml
    - 3-volumes/frontend-claim.yaml
    - 4-deployments/backend-deployment.yaml
    - 4-deployments/frontend-deployment.yaml
    - 5-services/backend-service.yaml
    - 5-services/frontend-service.yaml
    - 6-ingress/wordpres-ingress.yaml
    - 7-hpa/hpa-wordpress.yaml
