---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infra
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
