---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
    service: webserver
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: webserver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webserver
  labels:
    account: webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
      version: v1
  template:
    metadata:
      labels:
        app: webserver
        version: v1
    spec:
      serviceAccountName: webserver
      containers:
      - name: webserver
        image: docker.io/nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webserver-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webserver
spec:
  hosts:
  - "*"
  gateways:
  - webserver-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: webserver
        port:
          number: 80
